name: Docker-GPR
description: Build, Tag and Push images from a Dockerfile to the GPR

inputs:
  repo-token:
    description: Access token to use the api, use GITHUB_TOKEN silly, it's better
    required: true
  image-name:
    description: name for Docker image-name
    required: true

runs:
  using: "node12"
  main: main.js
